x-nr-sim-service:
  # develop:
  #   watch:
  #     - action: sync
  #       path: ./flows.json
  #       target: /data/flows.json
  &nr-sim
  environment:
    TZ: America/Boise
    # CREDENTIAL_FILE_KEY: "${NR_CREDENTIAL_KEY:?Set NR_CREDENTIAL_KEY in .env}"
    # ADMIN_USERNAME: "${NR_ADMIN_USERNAME:?Set NR_CREDENTIAL_KEY in .env}"
    # ADMIN_PWHASH: "${NR_ADMIN_PWHASH:?Set NR_CREDENTIAL_KEY in .env}"
  networks:
    av-vlan:
      # command: [ "--settings", "/settings.js" ]
      # configs:
      #   - source: nr-settings
      #     target: /settings.js
  restart: unless-stopped
  cap_add:
    - NET_ADMIN

services:
  flat-panel:
    <<: *nr-sim
    build:
      context: ./services/flat-panel
    networks:
      av-vlan:
        ipv4_address: 192.168.99.20
    volumes:
      - flat-panel-data:/data
      # - ./services/flat-panel/.data:/data:rw
    hostname: fp1
    ports:
      - "2880:1880"
  flat-panel-snmp:
    <<: *nr-sim
    image: ghcr.io/fullmetal-fred/snmp-emulator:latest
    networks:
      av-vlan:
        ipv4_address: 192.168.99.21
    hostname: fp1-snmp
    ports:
      - "1611:1611/udp"
  people-sensor:
    <<: *nr-sim
    build:
      context: ./services/people-sensor
    networks:
      av-vlan:
        ipv4_address: 192.168.99.30
    volumes:
      - people-sensor-data:/data
    hostname: ps1
    ports:
      - "3880:1880"
  video-bar:
    <<: *nr-sim
    build:
      context: ./services/video-bar
    networks:
      av-vlan:
        ipv4_address: 192.168.99.40
    volumes:
      - video-bar-data:/data
    hostname: vb1
    ports:
      - "4880:1880"

  # console:
  #   build:
  #     context: ./console
  #     args:
  #       ZBX_REPO_VERSION: ${ZBX_REPO_VERSION:?Set ZBX_REPO_VERSION in .env}
  #       ZBX_REPO_RELEASE: ${ZBX_REPO_RELEASE:?Set ZBX_REPO_RELEASE in .env}
  #       ZBX_REPO_PLATFORM: ${ZBX_REPO_PLATFORM:?Set ZBX_REPO_PLATFORM in .env}
  #   environment:
  #     - TZ=America/Boise
  #   networks:
  #     av-vlan:
  #       ipv4_address: "192.168.99.5"
  #   volumes:
  #     - console-data:/home/fullmetal-fred
  #   tty: true
  #   stdin_open: true
  #   stop_grace_period: 1s
  #   hostname: console

  zabbix-proxy:
    image: ghcr.io/fullmetal-fred/zabbix-proxy:latest
    networks:
      - av-vlan
    labels:
      com.zabbix.os: "Ubuntu"
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST:?Set ZBX_SERVER_HOST in .env}
      ZBX_HOSTNAME: ${ZBX_PROXY_HOSTNAME:?Set ZBX_PROXY_HOSTNAME in .env}
      ZBX_PROXYMODE: 0
      ZBX_ENABLEREMOTECOMMANDS: 1
      TZ: America/Boise
      ZBX_WEBDRIVERURL: chrome:4444
    hostname: zabbix-proxy

  chrome:
    image: selenium/standalone-chrome:latest
    networks:
      - av-vlan
    hostname: chrome
    shm_size: 2gb
    ports:
      - 4444:4444
      - 7900:7900

volumes:
  console-data:
  flat-panel-data:
  people-sensor-data:
  video-bar-data:
networks:
  av-vlan:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: "192.168.99.0/24"
          # ip_range: "192.168.99.128/25"
          gateway: "192.168.99.1"

# configs:
#   nr-settings:
#     file: ./node-red-settings.tpl.js
